models:
  - name: face-detection-retail-0004

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   face-detection-retail-0004/INT8/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/INT8/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - GPU32
        device: GPU
        model:   face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - GPU16
        device: GPU
        model:   face-detection-retail-0004/FP16/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        device: MYRIAD
        model:   face-detection-retail-0004/FP16/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        device: HDDL
        model:   face-detection-retail-0004/FP16/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FPGA16
        device: HETERO:FPGA,CPU
        model:   face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP16_TinyYolo.aocx

      - framework: dlsdk
        tags:
          - FPGA11
        device: HETERO:FPGA,CPU
        model:   face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP11_CaffeMobileNet.aocx

    datasets:
      - name: wider
        data_source: WIDER_val/images
        annotation_conversion:
          converter: wider
          annotation_file: wider_face_split/wider_face_val_bbx_gt.txt

        preprocessing:
          - type: resize
            size: 300

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.0
            apply_to: prediction

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
