models:
  - name: text-detection-0002

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        device: CPU
        model:   text-detection-0002/FP32/text-detection-0002.xml
        weights: text-detection-0002/FP32/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - GPU32
        device: GPU
        model:   text-detection-0002/FP32/text-detection-0002.xml
        weights: text-detection-0002/FP32/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2

      - framework: dlsdk
        tags:
          - GPU16
        device: GPU
        model:   text-detection-0002/FP16/text-detection-0002.xml
        weights: text-detection-0002/FP16/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2

      - framework: dlsdk
        device: MYRIAD
        model:   text-detection-0002/FP16/text-detection-0002.xml
        weights: text-detection-0002/FP16/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2

      - framework: dlsdk
        device: HDDL
        model:   text-detection-0002/FP16/text-detection-0002.xml
        weights: text-detection-0002/FP16/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2

      - framework: dlsdk
        tags:
          - FPGA16
        device: HETERO:FPGA.CPU
        model:   text-detection-0002/FP32/text-detection-0002.xml
        weights: text-detection-0002/FP32/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP16_MobileNet_Clamp.aocx

      - framework: dlsdk
        tags:
          - FPGA11
        device: HETERO:FPGA.CPU
        model:   text-detection-0002/FP32/text-detection-0002.xml
        weights: text-detection-0002/FP32/text-detection-0002.bin
        adapter:
          type: text_detection
          pixel_link_out: pixel_link/add_2
          pixel_class_out: pixel_cls/add_2
        cpu_extensions: AUTO
        bitstream: 2019R1_A10DK_FP11_MobileNet_Clamp.aocx

    datasets:
      - name: ICDAR2015

        data_source: ICDAR15_DET_validation/ch4_test_images
        annotation_conversion:
          converter: icdar15_detection
          data_dir: ICDAR15_DET_validation/gt

        preprocessing:
          - type: resize
            dst_width: 1280
            dst_height: 768

        postprocessing:
          - type: cast_to_int
          - type: filter
            area_range: 300, 980993
            height_range: 10
            width_range: 10
            apply_to: prediction
            remove_filtered: True
          - type: clip_points
            apply_to: prediction

        metrics:
          - type: text_detection
            name: f-measure
            ignore_difficult: True
